### PR TITLE
Fix ] in the if statement on line 64

### PR DESCRIPTION
**Pull request by damacus**
- Also fixes a number of shellcheck errors which prevents future errors

### CODE REVIEW

**Comment by damacus** [comment]
I'm guessing this should probably get fixed in the wrapper/template script repo. @Gadgetoid want me to try and fix it over there?

**Comment by Gadgetoid** [comment]
> I'm guessing this should probably get fixed in the wrapper/template script repo. @Gadgetoid want me to try and fix it over there?

Yes please, the boilerplate has a work-in-progress branch with all the latest changes here - https://github.com/pimoroni/boilerplate-python/pull/13

I'm in the process of migrating dozens of libraries, see: https://github.com/pimoroni/boilerplate-python/issues/16 - so it would be really helpful to get this stuff right!

**Comment by damacus** [comment]
Ace. I'll try and lend a hand over there. I actually can't see why that particular error crept on! 

Keep up the awesome work 😎

**Comment by Gadgetoid** [comment]
> I actually can't see why that particular error crept on!

I can 😭 I'm not quite cut out to coordinate this massive upheaval of so many projects, so my brain tends to wander and miss things.

**Comment by damacus** [comment]
👍🏼 I've found a decent action I'll make a Pr later today

**Comment by Gadgetoid** [comment]
Ooh, interesting! I smashed something together based on our exiting Make-based workflow (and fixed all the warnings and style suggestions), but the Action might be preferable just for better error reporting - https://github.com/pimoroni/boilerplate-python/commit/5e294af079b65f79c169023e437276794c4af59d

**Pull request merged**
